APPLICATION = stm32_eth_gnrc
include ../Makefile.tests_common

USEMODULE += gnrc_ipv6_default
USEMODULE += gnrc_icmpv6_echo
USEMODULE += gnrc_netdev_default
USEMODULE += auto_init_gnrc_netif
USEMODULE += gnrc_udp
USEMODULE += gnrc_sock_udp
include $(RIOTBASE)/Makefile.include
